name: Keep Server Active

on:
  workflow_dispatch:  # Allows for manual triggering
  schedule:
    - cron: "*/8 * * * *"  # Runs every 8 minutes and 33 seconds

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to keep server active
        run: |
          agents=("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" 
                  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15" 
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15" 
                  "Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36"
                  "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"
                  "Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile Safari/605.1.15"
                  "Mozilla/5.0 (Linux; Android 9; SM-J530F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Mobile Safari/537.36"
                  "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
                  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36")

          endpoints=("https://www.getyourtutorsl.com" 
                     "https://www.getyourtutorsl.com/aboutus" 
                     "https://www.getyourtutorsl.com/login")

          agent=${agents[$RANDOM % ${#agents[@]}]}
          endpoint=${endpoints[$RANDOM % ${#endpoints[@]}]}
          
          curl -I -A "$agent" "$endpoint" || echo "Request failed"
